services:
    web_topup_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web_topup_app
        restart: always
        env_file:
            - .env
        volumes:
            - app_code:/var/www/html # Share codebase hasil build ke volume
            - storage_data:/var/www/html/storage # Persistent storage untuk upload user
        networks:
            - shared_network

    web_topup_worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web_topup_worker
        restart: always
        env_file:
            - .env
        command: php artisan queue:work --tries=3 --timeout=90
        volumes:
            - app_code:/var/www/html # Menggunakan kode yang sama dari volume
            - storage_data:/var/www/html/storage
        networks:
            - shared_network

    web_topup_nginx:
        image: nginx:alpine
        container_name: web_topup_nginx
        restart: always
        depends_on:
            - web_topup_app
        ports:
            - "8999:80"
        volumes:
            - app_code:/var/www/html:ro # Nginx membaca asset public secara Read-Only
            - storage_data:/var/www/html/storage:ro
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - shared_network

volumes:
    storage_data:
    app_code:

networks:
    shared_network:
        external: true # PENTING: Menggunakan shared_network yang dibuat oleh stack MySQL
